<?php
class STCAPI{
	public $networks;

	public function __construct($source){
		$this->source = $source;
		$this->networks = array(
			'web2_0' => array(
				'name' => 'Web 2.0 Commando',
				'slug' => 'web2_0',
				'secret' => 'Password',
				'identifier' => 'Email',			
				'url' => 'https://ldg5.com/',
				'picture' => "{$this->source->plugin_url}views/images/favicon.ico",
				'description' => 'Tier\'ed backlinking',
			),
			'friendfeed' => array(
				'name' => 'FriendFeed',
				'slug' => 'friendfeed',
				'secret' => 'Remote Key',
				'identifier' => 'Remote Nickname',			
				'url' => 'https://friendfeed.com/',
				'picture' => "{$this->source->plugin_url}views/images/friendfeed.png",
				'description' => 'FriendFeed is a service that makes it easy '.
							'to share with friends online',
			),
			'twitter' => array(
				'name' => 'Twitter',
				'slug' => 'twitter',
				'oauth' => true,
				'secret' => 'Password',
				'identifier' => 'Username',			
				'url' => 'https://twitter.com/',
				'picture' => "{$this->source->plugin_url}views/images/twitter.png",
				'description' => 'Social networking',
			),
			'plurk' => array(
				'name' => 'Plurk',
				'slug' => 'plurk',
				'oauth' => true,
				'secret' => 'Password',
				'identifier' => 'Username',			
				'url' => 'http://www.plurk.com/',
				'picture' => "{$this->source->plugin_url}views/images/plurk.png",
				'description' => 'Social networking',
			),
			'livejournal' => array(
				'name' => 'Live Journal',
				'slug' => 'livejournal',
				'secret' => 'Password',
				'identifier' => 'Username',			
				'url' => 'http://www.livejournal.com/',
				'picture' => "{$this->source->plugin_url}views/images/livejournal.png",
				'description' => 'Blurring the lines between blogging and social networking.',
			),
			'diigo' => array(
				'name' => 'Diigo',
				'slug' => 'diigo',
				'secret' => 'Password',
				'identifier' => 'Username',			
				'url' => 'https://www.diigo.com/',
				'picture' => "{$this->source->plugin_url}views/images/diigo.png",
				'description' => 'Social bookmarking network.',
			),
			'delicious' => array(
				'name' => 'Delicious',
				'slug' => 'delicious',
				'secret' => 'Password',
				'identifier' => 'Username',			
				'url' => 'https://delicious.com/',
				'picture' => "{$this->source->plugin_url}views/images/delicious.png",
				'description' => 'Social bookmarking network.',
			),
			'pinterest' => array(
				'name' => 'Pinterest',
				'slug' => 'pinterest',
				'secret' => 'Password',
				'identifier' => 'Email',			
				'url' => 'https://pinterest.com/',
				'picture' => "{$this->source->plugin_url}views/images/pinterest.png",
				'description' => 'Visual bookmarks.',
			),
			'stumbleupon' => array(
				'name' => 'StumbleUpon',
				'slug' => 'stumbleupon',
				'secret' => 'Password',
				'identifier' => 'Username',			
				'url' => 'http://www.stumbleupon.com/',
				'picture' => "{$this->source->plugin_url}views/images/stumbleupon.png",
				'description' => 'Visual bookmarks.',
			),
			'tumblr' => array(
				'name' => 'Tumblr',
				'slug' => 'tumblr',
				'oauth' => true,
				'secret' => 'Password',
				'identifier' => 'Username',			
				'url' => 'https://www.tumblr.com/',
				'picture' => "{$this->source->plugin_url}views/images/tumblr.png",
				'description' => 'Personal blog network',
			),
			'wordpress' => array(
				'name' => 'Wordpress',
				'slug' => 'wordpress',
				'oauth' => true,
				'secret' => 'Password',
				'identifier' => 'Username',			
				'url' => 'https://wordpress.com/',
				'picture' => "{$this->source->plugin_url}views/images/wordpress.png",
				'description' => 'Personal blog network',
			),
			'linkedin' => array(
				'name' => 'LinkedIn',
				'slug' => 'linkedin',
				'oauth' => true,
				'secret' => 'Password',
				'identifier' => 'Username',			
				'url' => 'https://www.linkedin.com/',
				'picture' => "{$this->source->plugin_url}views/images/linkedin.png",
				'description' => 'Professional social network',
			),
			'gplus' => array(
				'name' => 'G+',
				'slug' => 'gplus',
				'secret' => 'Password',
				'identifier' => 'Email',		
				'url' => 'https://plus.google.com/',
				'picture' => "{$this->source->plugin_url}views/images/gplus.jpg",
				'description' => 'Google social network',
			),
			'facebook' => array(
				'name' => 'Facebook',
				'slug' => 'facebook',
				'oauth' => true,			
				'url' => 'https://www.facebook.com/',
				'picture' => "{$this->source->plugin_url}views/images/facebook.png",
				'description' => 'Social network',
			),
			'scribd' => array(
				'name' => 'Scribd',
				'slug' => 'scribd',
				'secret' => 'API Secret',
				'identifier' => 'API Key',			
				'url' => 'http://www.scribd.com/',
				'picture' => "{$this->source->plugin_url}views/images/scribd.png",
				'description' => 'Free and paid document sharing',
			),
		);
	}
	
}
?>
